# Generated by Django 2.0.3 on 2018-03-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_auto_20180313_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='time_l1',
            field=models.FloatField(default=999.9),
        ),
        migrations.AddField(
            model_name='player',
            name='time_l2',
            field=models.FloatField(default=999.9),
        ),
        migrations.AddField(
            model_name='player',
            name='time_l3',
            field=models.FloatField(default=999.9),
        ),
    ]
