# Generated by Django 2.0.3 on 2018-04-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_auto_20180329_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='solution_seen_l0',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='solution_seen_l1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='solution_seen_l2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='solution_seen_l3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='solution_seen_l4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='solution_seen_l5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='solution_seen_l6',
            field=models.BooleanField(default=False),
        ),
    ]
